import { createConfig } from "@privy-io/wagmi";
import {
  mainnet,
  optimism,
  cronos,
  bsc,
  gnosis,
  unichain,
  polygon,
  monad,
  sonic,
  worldchain,
  metis,
  soneium,
  mantle,
  base,
  plasma,
  arbitrum,
  celo,
  avalanche,
  ink,
  linea,
  berachain,
  blast,
  scroll,
  hyperEvm,
} from "wagmi/chains";
import { http } from "viem";

export const SUPPORTED_CHAINS = [
  mainnet,
  optimism,
  cronos,
  bsc,
  gnosis,
  unichain,
  polygon,
  monad,
  sonic,
  worldchain,
  metis,
  soneium,
  mantle,
  base,
  plasma,
  arbitrum,
  celo,
  avalanche,
  ink,
  linea,
  berachain,
  blast,
  scroll,
  hyperEvm,
] as const;

export const wagmiConfig = createConfig({
  chains: SUPPORTED_CHAINS,
  transports: {
    [mainnet.id]: http(),
    [optimism.id]: http(),
    [cronos.id]: http(),
    [bsc.id]: http(),
    [gnosis.id]: http(),
    [unichain.id]: http(),
    [polygon.id]: http(),
    [monad.id]: http(),
    [sonic.id]: http(),
    [worldchain.id]: http(),
    [metis.id]: http(),
    [soneium.id]: http(),
    [mantle.id]: http(),
    [base.id]: http(),
    [plasma.id]: http(),
    [arbitrum.id]: http(),
    [celo.id]: http(),
    [avalanche.id]: http(),
    [ink.id]: http(),
    [linea.id]: http(),
    [berachain.id]: http(),
    [blast.id]: http(),
    [scroll.id]: http(),
    [hyperEvm.id]: http(),
  },
});
